---
# =============================================================================
# Common variables
# =============================================================================

vault__ansible_host__list:
  node1: "0.0.0.0"
  node2: "0.0.0.0"

# =============================================================================
# Bootstrap variables
# =============================================================================

vault__iac__bootstrap__hostname__list:
  node1: "hostname"
  node2: "hostname"

# =============================================================================
# Initial connection details
# =============================================================================

vault__initial_ansible_port__list:
  node1: 0
  node2: 0

vault__initial_ansible_user__list:
  node1: "root"
  node2: "cloud_user"

vault__initial_ansible_user_initial_password__list:
  node1: "initial_password"
  node2: ~

vault__initial_ansible_user_password__list:
  node1: "password"
  node2: "password"

vault__initial_ansible_user_initial_ssh_key__list:
  node1: ~
  node2: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    initial_ssh_key
    -----END OPENSSH PRIVATE KEY-----

vault__initial_ansible_user_ssh_key__list:
  node1: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    ssh_key
    -----END OPENSSH PRIVATE KEY-----
  node2: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    ssh_key
    -----END OPENSSH PRIVATE KEY-----


vault__initial_ansible_user_ssh_public_key__list:
  node1: "ssh-ed25519 AAAA... initial_user_public_key"
  node2: "ssh-ed25519 AAAA... initial_user_public_key"

# =============================================================================
# Connection variables
# =============================================================================

vault__ansible_port__list:
  node1: 0
  node2: 0

vault__ansible_user__list:
  node1: "ansible_user"
  node2: "ansible_user"

vault__ansible_user_password__list:
  node1: "password"
  node2: "password"

vault__ansible_user_ssh_key__list:
  node1: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    ssh_key
    -----END OPENSSH PRIVATE KEY-----
  node2: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    ssh_key
    -----END OPENSSH PRIVATE KEY-----

vault__ansible_user_ssh_public_key__list:
  node1: "ssh-ed25519 AAAA... deployer_user_public_key"
  node2: "ssh-ed25519 AAAA... deployer_user_public_key"
