iac__common__hostname: "{{ _iac__defaults__hostname }}"
iac__common__timezone: "{{ _iac__defaults__timezone }}"
iac__common__directory_mode: "{{ _iac__defaults__directory_mode }}"
iac__common__file_mode: "{{ _iac__defaults__file_mode }}"
iac__common__home_directory_mode: "{{ _iac__defaults__home_directory_mode }}"
iac__common__ssh_directory_mode: "{{ _iac__defaults__ssh_directory_mode }}"
iac__common__ssh_file_mode: "{{ _iac__defaults__ssh_file_mode }}"
iac__common__ssh_port: "{{ _iac__defaults__ssh_port }}"
iac__common__custom_ssh_port: "{{ _iac__defaults__custom_ssh_port }}"
iac__common__ssh_user: "{{ _iac__defaults__ssh_user }}"
iac__common__ssh_service_name: "{{ _iac__defaults__ssh_service_name }}"
iac__common__ssh_dropin_file_path: "{{ _iac__defaults__ssh_dropin_file_path }}"
iac__common__repository_base_directory: "{{ _iac__defaults__repository_base_directory }}"
iac__common__ansible_base_directory: "{{ _iac__defaults__ansible_base_directory }}"
iac__common__home_directory: "{{ _iac__defaults__home_directory }}"
iac__common__ssh_base_directory: "{{ _iac__defaults__ssh_base_directory }}"
iac__common__ansible_ssh_private_key_file_directory: "{{ _iac__defaults__ansible_ssh_private_key_file_directory }}"
iac__common__ansible_ssh_private_key_file: "{{ _iac__defaults__ansible_ssh_private_key_file }}"
iac__common__ansible_ssh_private_key_file_directory_mode: "{{ _iac__defaults__ansible_ssh_private_key_file_directory_mode }}"
iac__common__ansible_ssh_private_key_file_mode: "{{ _iac__defaults__ansible_ssh_private_key_file_mode }}"
iac__common__ansible_artifacts_directory: "{{ _iac__defaults__ansible_artifacts_directory }}"
