# =============================================================================
# Required variables
# =============================================================================
iac__ansible_ssh_private_key: ~